import sys
import os
import json
from typing import Dict, Any

# Ensure we can import from backend
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

try:
    from backend.Agents.orchestrator import AgentCollaborationTeam
except ImportError as e:
    print(f"Error: Could not import backend. Please run this script from the root directory. Details: {e}")
    sys.exit(1)

def print_separator(title: str = ""):
    width = 60
    if title:
        padding = (width - len(title) - 2) // 2
        print("\n" + "=" * padding + f" {title} " + "=" * padding)
    else:
        print("\n" + "=" * width)

def run_cli():
    print_separator("Gen Alpha Agent Collaboration CLI")
    print("Welcome! Aapki specialized engineering team tayyar hai.")
    print("Aap jo bhi task/feature PeriMatrix AI ke liye banana chahte hain,")
    print("wo yahan type karein. Humare specialized agents milkar use solve karenge!")
    print("Type 'exit' or 'quit' to close the program.\n")

    # Instantiate the Orchestrator Team
    orchestrator = AgentCollaborationTeam()
    session_id = "cli_collaboration_session"

    while True:
        try:
            problem = input("\n👉 Aap is team se kya banwana chahte hain? \n> ")
            if not problem.strip():
                continue

            if problem.strip().lower() in ["exit", "quit"]:
                print("\nAlvida! Aapki engineering team hamesha aapki madad ke liye tayyar hai. 🚀")
                break

            print_separator("Planning Phase")
            print("PlannerAgent: Analyzing the goal and breaking it down into subtasks...")

            # Run the multi-agent collaboration pipeline
            result = orchestrator.solve_problem(session_id=session_id, problem_statement=problem)

            print("\n📋 Task Breakdown:")
            for idx, subtask in enumerate(result.get("subtasks", [])):
                print(f"  {idx+1}. [{subtask.get('agent')}] -> {subtask.get('task')}")

            print_separator("Execution Phase")
            for step in result.get("execution_steps", []):
                print(f"⚙️ Running Step {step.get('step')}: {step.get('agent')} is executing...")
                print(f"   Task: {step.get('task')}")
                # Indent and print a preview of the output
                res_preview = step.get('result', '')
                if len(res_preview) > 250:
                    res_preview = res_preview[:250] + "\n   ...(truncated for preview)..."
                print(f"   Result:\n   {res_preview}\n")

            print_separator("Synthesis Phase")
            print("Lead Orchestrator: Combining and refining the work of all agents...")
            print("\n✨ FINAL SOLUTION GENERATED BY THE TEAM:")
            print(result.get("final_solution"))
            print_separator("Collaboration Session Complete")

        except KeyboardInterrupt:
            print("\nSession interrupted. Alvida!")
            break
        except Exception as e:
            print(f"\n❌ Ek error aayi: {e}")

if __name__ == "__main__":
    run_cli()
